services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD
  gitolite:
    image: jgiannuzzi/gitolite
    ports:
      - 22:22
    volumes:
      - gitolite-sshkeys:/etc/ssh/keys
      - gitolite-git:/var/lib/git
    environment:
      - SSH_KEY
  giz:
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "1"
    environment:
      - DEBUG=True
      - GITOLITE_HOST=gitolite
      - GITOLITE_PORT=22
      - GITOLITE_KEY
      - POSTGRES_PASSWORD
      - SECRET_KEY
    depends_on:
      - gitolite
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./giz:/usr/share/www
      - gitolite-git:/usr/share/git:ro
      - static:/usr/share/giz/static

volumes:
  gitolite-sshkeys:
  gitolite-git:
  static:
