services:
  gitolite:
    image: jgiannuzzi/gitolite
    ports:
      - 22:22
    volumes:
      - gitolite-sshkeys:/etc/ssh/keys
      - gitolite-git:/var/lib/git
    environment:
      - SSH_KEY
  redis:
    image: redis:5
    ports:
      - 6379:6379
  nginx:
    build: services/nginx
    volumes:
      - static:/usr/share/www/static:ro
    ports:
      - 80:80
      - 443:443
  giz:
    build: .
    logging:
      #driver: "journald"
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "1"
          #tag: mytag
    environment:
      #- PYTHONUNBUFFERED=1
      - GITOLITE_HOST=gitolite
      - GITOLITE_PORT=22
      - GITOLITE_KEY
      - PROD=True
      - SECRET_KEY
    depends_on:
      - gitolite
      - redis
      - nginx
        # database
    ports:
      - 8000:8000
    volumes:
      - ./giz:/usr/share/www
      - gitolite-sshkeys:/root/keys:ro
      - gitolite-git:/usr/share/git:ro
      - static:/usr/share/giz/static
    command: gunicorn -c /usr/share/gunicorn-conf.py

volumes:
  gitolite-sshkeys:
  gitolite-git:
  database:
  static:
# django:
