# This is (mostly) just a copy of docker-compose.yml
# However, we there's a few changes to the `giz` service:
# * command is set to gunicorn
# * no ports are exposed
# * DEBUG is not set, and PROD=True
# * the source code is not mounted, but rather added
services:
  nginx:
    build: services/nginx
    volumes:
      - static:/usr/share/www/static:ro
      - /root/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
  redis:
    image: redis:5
    #ports:
    #  - 6379:6379
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - /root/data:/var/lib/postgresql/data
  gitolite:
    image: jgiannuzzi/gitolite
    ports:
      - 22:22
    volumes:
      - gitolite-sshkeys:/etc/ssh/keys
      - gitolite-git:/var/lib/git
    environment:
      - SSH_KEY
  giz:
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "1"
    environment:
      - PROD=True
      - GITOLITE_HOST=gitolite
      - GITOLITE_PORT=22
      - GITOLITE_KEY
      - POSTGRES_PASSWORD
      - SECRET_KEY
    depends_on:
      - nginx
      - redis
      - gitolite
      - postgres
    volumes:
      - gitolite-sshkeys:/root/keys:ro
      - gitolite-git:/usr/share/git:ro
      - static:/usr/share/giz/static
    command: gunicorn -c /usr/share/gunicorn-conf.py

volumes:
  gitolite-sshkeys:
  gitolite-git:
  static:
