services:
  gitolite:
    image: jgiannuzzi/gitolite
    ports:
      - 22:22
    volumes:
      - gitolite-sshkeys:/etc/ssh/keys
      - gitolite-git:/var/lib/git
    environment:
      - SSH_KEY
  redis:
    image: redis:5
    ports:
      - 6379:6379
  tonic:
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "1"
    environment:
      #- PYTHONUNBUFFERED=1
      - DEBUG=True
    depends_on:
      - redis
    ports:
      - 8000:8000
    volumes:
      - ./tonic:/usr/share/www
    command: python3 manage.py runserver 0.0.0.0:8000

volumes:
  gitolite-sshkeys:
  gitolite-git:
