#!/usr/bin/env sh

source setupenv

docker-compose -f docker-compose-prod.yml build
docker-compose -f docker-compose-prod.yml up -d

docker-compose exec nginx certbot --nginx -n --agree-tos -m 'YOUREMAIL@EXAMPLE.ORG' --domains giz.sh,www.giz.sh
#docker-compose exec postgres psql -U postgres -c 'create database giz;'

docker-compose exec giz python manage.py makemigrations --noinput
docker-compose exec giz python manage.py migrate --noinput
docker-compose exec giz python manage.py collectstatic --noinput
